Auto Testing multiple charts in specified folder
datreeio/action-datree pull request #15
Opened 2022-10-07 13:45 UTC by MVladislav

Implemented script from here: https://github.com/datreeio/helm-datree#testing-multiple-charts
for auto search all helm project under an specified folder, to not need to add for every single helm project an own config runtime.

Also added the line:
` echo "**Source path:** ${1}" >>"$GITHUB_STEP_SUMMARY"`
to know which project was checked when multi helm project folders will be checked.

All other processes should be work as before, only helm is changed.

2022-10-11 10:41 UTC, hadar-co commented
Hi @MVladislav thanks for this PR, looks great!
I left some comments, please have a look:)

2022-10-11 13:11 UTC, hadar-co requested changes

2022-10-11 13:11 UTC, hadar-co commented on entrypoint.sh
> +if [ "$isHelmChart" = "true" ]; then
since the helm plugin runs the Datree CLI, the interesting version here is that of the CLI and not the plugin. Please leave as it was:)

2022-10-11 13:11 UTC, hadar-co commented on entrypoint.sh
> +  datree test "$inputpath" $cliArguments
When using globs, this will not work. Please change `"$inputpath"` to `$inputpath` (remove the quotes). Something in the way Github parses/substitutes variables causes this to fail, which is why there were no quotes there in the first place.

2022-10-11 13:11 UTC, hadar-co commented on entrypoint.sh
> +  datree kustomize test "$inputpath" $cliArguments -- $kustomizeArgs
Same as the comment below about `"$inputpath"` (remove quotes).

2022-10-16 00:20 UTC, MVladislav commented on entrypoint.sh
> +  datree kustomize test "$inputpath" $cliArguments -- $kustomizeArgs
alright, will be reverted.

Do you know if the same happens with the helm version? 
Here `$dir` is in quotes:
`helm datree test "$dir" $cliArguments -- $helmArgs`
i will leave this for now in quotes.

2022-10-16 09:20 UTC, hadar-co commented on entrypoint.sh
> +  datree kustomize test "$inputpath" $cliArguments -- $kustomizeArgs
when using helm, you shouldn't use globs since your PR now makes it recursive:) so no need to remove the quotes.
I'll make it clearer in the readme

2022-10-16 09:22 UTC, hadar-co approved these changes

2022-10-16 09:28 UTC, merged